package com.stablebridge.prreview.domain.service;

import static com.stablebridge.prreview.domain.model.IssueSeverity.CRITICAL;
import static com.stablebridge.prreview.domain.model.IssueSeverity.WARNING;

import com.stablebridge.prreview.domain.model.CodeAnalysis;
import com.stablebridge.prreview.domain.model.CodeIssue;
import com.stablebridge.prreview.domain.model.IssueSeverity;
import com.stablebridge.prreview.domain.model.PrDiff;
import com.stablebridge.prreview.domain.model.ReviewSuggestion;
import org.springframework.stereotype.Service;

@Service
public class ReviewFormatter {

    public String format(PrDiff diff, CodeAnalysis analysis) {
        var sb = new StringBuilder();
        sb.append("## AI Code Review: %s\n\n".formatted(diff.title()));
        sb.append("### Overview\n%s\n\n".formatted(analysis.overallAssessment()));

        appendIssues(sb, analysis);
        appendSuggestions(sb, analysis);

        sb.append("\n---\n*Generated by PR Review Agent (Embabel + Spring AI)*");
        return sb.toString();
    }

    private void appendIssues(StringBuilder sb, CodeAnalysis analysis) {
        if (analysis.issues().isEmpty()) {
            return;
        }
        sb.append("### Issues Found\n");
        for (CodeIssue issue : analysis.issues()) {
            var icon = severityIcon(issue.severity());
            sb.append("- %s **[%s]** `%s` (%s): %s\n".formatted(
                    icon,
                    issue.severity().name(),
                    issue.filename(),
                    issue.lineReference(),
                    issue.description()));
        }
        sb.append("\n");
    }

    private void appendSuggestions(StringBuilder sb, CodeAnalysis analysis) {
        if (analysis.suggestions().isEmpty()) {
            return;
        }
        sb.append("### Suggestions\n");
        for (ReviewSuggestion suggestion : analysis.suggestions()) {
            sb.append("- `%s`: %s\n".formatted(
                    suggestion.filename(), suggestion.description()));
            if (suggestion.suggestedCode() != null) {
                sb.append("  ```\n  %s\n  ```\n".formatted(suggestion.suggestedCode()));
            }
        }
    }

    private String severityIcon(IssueSeverity severity) {
        if (severity == CRITICAL) {
            return "[CRITICAL]";
        }
        if (severity == WARNING) {
            return "[WARNING]";
        }
        return "[INFO]";
    }
}
